### ISSUE TITLE
Repo in package.json

### ISSUE THREAD

**Issue by jonaskello** [Vincit/knex-db-manager#22]
Nice lib, just checking it out for my needs to initialize databases that use knex migrations.

I noticed the `reposiotry` field in `package.json` is pointing to a fork rather than this repo. So for example the number of issues here is not reflected at npmjs.org. Just wanted to check if that is correct?

**Comment by elhigu** [comment]
Nice catch, code was originally in my own repo, I forgot to fix the link when moving it here. I'll be fixing all the stuff you found pretty soon when I'm taking some time for maintaining this. It is nice to have users outside of our own staff for this 👍  Btw. if you haven't checked out our ORM objection.js you might be interested.
