### ISSUE TITLE
Link npm module to this repo instead of fork

### ISSUE THREAD

**Issue by krishnagopinath** [Vincit/knex-db-manager#28]
First of all, thanks for this great project! :)

I saw that the [npm package of `knex-db-manager`](https://www.npmjs.com/package/knex-db-manager) points [to a fork of this repo](https://github.com/elhigu/knex-db-manager), and this fork [doesn't support MySQL](https://github.com/elhigu/knex-db-manager/blob/master/tests/database-manager.spec.js#L60) yet. 

As of now, I'm using the version of `knex-db-manager` in this repo by running this:

```
npm i Vincit/knex-db-manager
```

However, it would be great if the npm was linked to this repo as opposed to the fork. 

Thanks again! 😄

**Comment by elhigu** [comment]
Thanks for reporting :) I'll fix that pretty soon, when I'm giving this some maintenance time. Closing as duplicate #22
