### ISSUE TITLE
Encode URI components

### ISSUE THREAD

**Issue by gynnantonix** [Vincit/knex-db-manager#57]
https://github.com/Vincit/knex-db-manager/blob/99771ceeb29636621a600523810a7bb99f760fa6/lib/PostgresDatabaseManager.js#L260

DB passwords that contain non-URL-safe characters (e.g. hash marks) must be encoded so that pg can properly parse the connection string.  Wrapping them in `encodeURIComponent()` should do the trick.

**Comment by elhigu** [comment]
Need to write test case and setup test databases to use hashes and colons in passwords.

**Comment by elhigu** [comment]
Fixed in next release.
