### ISSUE TITLE
knex timeout on migrateDb() call

### ISSUE THREAD

**Issue by proton1k** [Vincit/knex-db-manager#92]
Hi,

I've been struggling to deploy the initial version of a nodejs app with Postgres on Digitalocean.
I get the 
```
Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```
ERROR on the [migrateDb](https://github.com/Vincit/knex-db-manager/blob/155b8e50a4503b5601767c09024099230b5ffbe0/lib/DatabaseManager.js#L125-L128) function call. How can I find out what exactly is happening on the `knex.migrate.latest()` used within and traceback to the actual issue?

**Comment by elhigu** [comment]
Setup DEBUG=knex:* environment variable in your run environment and you should see a lot more information what is happening i inside knex. Also the error is not related to knex-db-manager, it is coming from knex. You might want to check your configuration that it is correct and DB is available.
